version: "3.8"
services:
    base_image:
        build:
            context: .
            dockerfile: ./devops/base/Dockerfile
        container_name: fantasy_base_image
        command: sleep 1000

    django: &django
        restart: always
        build:
            context: .
            dockerfile: ./devops/django/Dockerfile
        volumes:
            - .:/project
            - static_volume:/app/var/static
        expose:
            - 8000
        env_file:
            - .env
        depends_on:
            - postgres
            - base_image

    postgres:
        restart: always
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data/
        env_file:
            - .env

    nginx:
        build:
            context: .
            dockerfile: ./devops/nginx/Dockerfile
        volumes:
            - static_volume:/app/var/static
        ports:
            - 80:80
        depends_on:
            - django

    celery:
        <<: *django
        build:
            context: .
            dockerfile: ./devops/celery/Dockerfile
        ports: []
        depends_on:
            - redis

    celery-beat:
        <<: *django
        build:
            context: .
            dockerfile: ./devops/celery-beat/Dockerfile
        ports: []
        depends_on:
            - redis

    redis:
        image: redis
        ports:
            - "6379:6379"

volumes:
    postgres-data:
    static_volume:
